/** Static dummy data — Student Management UI */

export const CLASS_OPTIONS = ["6", "7", "8", "9", "10", "11", "12"];

export const GENDER_OPTIONS = [
  { value: "", label: "Select" },
  { value: "Female", label: "Female" },
  { value: "Male", label: "Male" },
  { value: "Other", label: "Other" },
];

/** Full form shape for add/edit (stepper). */
export function emptyStudentForm() {
  return {
    name: "",
    classGrade: "",
    section: "",
    rollNo: "",
    dateOfBirth: "",
    gender: "",
    fatherName: "",
    fatherPhone: "",
    fatherOccupation: "",
    fatherQualification: "",
    motherName: "",
    motherPhone: "",
    motherOccupation: "",
    motherQualification: "",
    address: "",
    city: "",
    state: "",
    zipCode: "",
    admissionDate: "",
    previousSchool: "",
    /** Legacy display — synced from parents on save when possible */
    parentName: "",
  };
}

export const INITIAL_STUDENTS = [
  {
    id: "stu-1",
    name: "Aditi Sharma",
    classGrade: "9",
    section: "A",
    rollNo: "901",
    parentName: "Rajesh Sharma",
    dateOfBirth: "2010-04-12",
    gender: "Female",
    fatherName: "Rajesh Sharma",
    fatherPhone: "+91 98765 11101",
    fatherOccupation: "Engineer",
    fatherQualification: "B.Tech",
    motherName: "Sunita Sharma",
    motherPhone: "+91 98765 11102",
    motherOccupation: "Teacher",
    motherQualification: "M.Ed",
    address: "12 Palm Grove, Sector 4",
    city: "Bengaluru",
    state: "Karnataka",
    zipCode: "560001",
    admissionDate: "2023-04-01",
    previousSchool: "Green Valley Public School",
  },
  {
    id: "stu-2",
    name: "Vihaan Mehta",
    classGrade: "9",
    section: "B",
    rollNo: "924",
    parentName: "Priya Mehta",
    dateOfBirth: "2010-09-21",
    gender: "Male",
    fatherName: "Amit Mehta",
    fatherPhone: "+91 98765 22201",
    fatherOccupation: "Consultant",
    fatherQualification: "MBA",
    motherName: "Priya Mehta",
    motherPhone: "+91 98765 22202",
    motherOccupation: "Architect",
    motherQualification: "B.Arch",
    address: "88 Lake View Rd",
    city: "Pune",
    state: "Maharashtra",
    zipCode: "411001",
    admissionDate: "2023-04-03",
    previousSchool: "City Montessori",
  },
  {
    id: "stu-3",
    name: "Ananya Iyer",
    classGrade: "10",
    section: "A",
    rollNo: "102",
    parentName: "Karthik Iyer",
    dateOfBirth: "2009-02-03",
    gender: "Female",
    fatherName: "Karthik Iyer",
    fatherPhone: "+91 98765 33301",
    fatherOccupation: "Doctor",
    fatherQualification: "MBBS",
    motherName: "Lakshmi Iyer",
    motherPhone: "+91 98765 33302",
    motherOccupation: "Researcher",
    motherQualification: "Ph.D",
    address: "5 Temple St",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600004",
    admissionDate: "2022-06-01",
    previousSchool: "Vidya Niketan",
  },
  {
    id: "stu-4",
    name: "Kabir Khan",
    classGrade: "8",
    section: "C",
    rollNo: "815",
    parentName: "Fatima Khan",
    dateOfBirth: "2011-11-18",
    gender: "Male",
    fatherName: "Imran Khan",
    fatherPhone: "+91 98765 44401",
    fatherOccupation: "Business",
    fatherQualification: "B.Com",
    motherName: "Fatima Khan",
    motherPhone: "+91 98765 44402",
    motherOccupation: "Designer",
    motherQualification: "B.Des",
    address: "Plot 4, Ring Road",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500032",
    admissionDate: "2024-04-10",
    previousSchool: "Springdale Primary",
  },
  {
    id: "stu-5",
    name: "Meera Nair",
    classGrade: "11",
    section: "A",
    rollNo: "112",
    parentName: "Suresh Nair",
    dateOfBirth: "2008-07-25",
    gender: "Female",
    fatherName: "Suresh Nair",
    fatherPhone: "+91 98765 55501",
    fatherOccupation: "Bank officer",
    fatherQualification: "B.Sc",
    motherName: "Deepa Nair",
    motherPhone: "+91 98765 55502",
    motherOccupation: "Nurse",
    motherQualification: "B.Sc Nursing",
    address: "Rose Cottage, NH66",
    city: "Kochi",
    state: "Kerala",
    zipCode: "682001",
    admissionDate: "2021-06-15",
    previousSchool: "Sacred Heart HS",
  },
  {
    id: "stu-6",
    name: "Arjun Desai",
    classGrade: "10",
    section: "B",
    rollNo: "118",
    parentName: "Divya Desai",
    dateOfBirth: "2009-12-05",
    gender: "Male",
    fatherName: "Vikram Desai",
    fatherPhone: "+91 98765 66601",
    fatherOccupation: "Lawyer",
    fatherQualification: "LL.B",
    motherName: "Divya Desai",
    motherPhone: "+91 98765 66602",
    motherOccupation: "Writer",
    motherQualification: "MA English",
    address: "19 Riverfront",
    city: "Ahmedabad",
    state: "Gujarat",
    zipCode: "380001",
    admissionDate: "2023-06-01",
    previousSchool: "Shanti Vidya Mandir",
  },
];
